# Nom du workflow
name: Deploy to Heroku

# Déclenchement du workflow sur chaque push sur la branche main
on:
  push:
    branches: [main]

# Jobs exécutés
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Étape 1 : Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Heroku CLI
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      # Étape 3 : Connexion à Heroku Container Registry
      - name: Login to Heroku Container Registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      # Étape 4 : Construire et pousser l’image Docker sur Heroku
      - name: Build and push Docker image
        run: heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }}

      # Étape 5 : Déployer l’application
      - name: Release Docker container on Heroku
        run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
